// All user-facing UI text (Filipino). Feedback lines come from the API.
export const t = {
  loading: 'Sandali lang...',
  loadingSession: 'Inihahanda ang sesyon...',
  loadingStory: 'Inihahanda ang kuwento...',
  loadingSummary: 'Ginagawa ang buod...',
  loadError: 'May problema. Subukan muli.',
  retry: 'Subukan muli',
  turnLabel: (n) => `Tanong ${n}`,
  learnerTurn: (name) => `Ikaw na, ${name}!`,
  listen: 'Pakinggan',
  instructions: {
    dictation_letters: 'Pakinggan ang salita. Buuin gamit ang mga titik.',
    dictation_syllables: 'Pakinggan ang salita. Buuin gamit ang mga pantig.',
    missing_letter: 'Pakinggan ang salita. Anong titik ang kulang?',
    sentence_builder: 'Pakinggan. Ayusin ang mga salita.',
  },
  modelLabel: 'Tingnan:',
  slotsLabel: 'Mga kahon para sa sagot',
  trayLabel: 'Mga tile na pagpipilian',
  emptySlot: (n) => `Bakanteng kahon ${n}`,
  fixedTile: (text, n) => `${text}, nakalagay na sa kahon ${n}`,
  placedTile: (text, n) => `${text}, nasa kahon ${n}. Pindutin para alisin.`,
  availableTile: (text) => `${text}. Pindutin para ilagay.`,
  clear: 'Burahin',
  check: 'Suriin',
  next: 'Susunod',
  // Generic fallback from CLAUDE.md, used while the API sends no feedback for wrong attempts.
  tryAgain: (name) => `Subukan natin ulit, ${name}!`,
  overlay: {
    title: 'Malapit na!',
    hints: {
      replay_by_syllable: 'Pakinggan ulit ang bawat pantig.',
      highlight_slot: 'Tingnan ang kahong may ilaw.',
      first_tile: 'Magsimula tayo sa unang kahon.',
    },
    retry: 'Subukan ulit',
    listenAgain: 'Pakinggan ulit',
    showAnswer: 'Ipakita ang sagot',
  },
  phases: {
    readAlong: 'Sabay na pagbasa',
    tiles: 'Mga tile',
    stories: 'Mga tanong sa kuwento',
  },
  tutorBar: {
    tutor: 'Tutor',
    skip: 'Laktawan',
    timeLeft: (time) => `Natitirang oras: ${time}`,
    timeUp: 'Tapos na ang oras',
  },
  login: {
    title: 'Pasok ng Tutor',
    prompt: 'Ilagay ang iyong PIN',
    digit: (d) => `Numero ${d}`,
    filled: (n, total) => `${n} sa ${total} numero`,
    delete: 'Bura',
    deleteLabel: 'Burahin ang huling numero',
    enter: 'Pumasok',
    demoNote: 'Demo: puwede ang kahit anong PIN.',
    error: 'May problema sa PIN. Subukan muli.',
  },
  group: {
    greeting: (name) => `Magandang araw, ${name}!`,
    question: 'Sino ang narito ngayon?',
    present: 'Narito',
    absent: 'Wala',
    count: (n) => `${n} bata ang narito.`,
    needOne: 'Pumili ng kahit isang bata.',
    start: 'Simulan ang sesyon',
  },
  // Tutor-facing (English for now, like signup): pick learners who already used AR.AI on this laptop.
  returning: {
    open: 'Returning learners',
    title: 'Returning learners',
    subtitle: 'Their progress is saved: no diagnostic again. Pick who is here today.',
    level: (n) => `Story level ${n}`,
    mastered: (n) => `${n} skills mastered`,
    last: (d) => (d ? `Last session ${d}` : 'No session yet'),
    use: (n) => `Start with ${n} learner${n === 1 ? '' : 's'}`,
    signUp: 'Sign up new learners',
    back: 'Back',
    none: 'No saved learners yet.',
  },
  readAlong: {
    heading: 'Sabay tayong magbasa',
    instruction: 'Pakinggan ang kuwento.',
    echo: 'Ngayon, sabay-sabay nating basahin!',
    repeat: 'Muling Pakinggan',
    nextParagraph: 'Susunod na talata',
    done: 'Tapos na',
    paragraphOf: (i, n) => `Talata ${i} ng ${n}`,
  },
  story: {
    listen: 'Pakinggan ang tanong',
    instruction: 'Piliin ang tamang sagot.',
    choicesLabel: 'Mga pagpipilian',
  },
  summary: {
    subtitle: 'Para sa tutor',
    title: 'Buod ng sesyon',
    nextFocus: 'Susunod na pagtuunan:',
    groupNote: 'Paalala sa grupo:',
    newSession: 'Bagong sesyon',
  },
  progress: {
    stars: (n) => `${n} bituin`,
    questions: (n, total) => `${n} sa ${total} tanong`,
  },
  sheet: {
    print: 'Ilimbag ang Magsanay Sheet',
    preparing: 'Inihahanda...',
    title: 'Magsanay Tayo!',
    name: 'Pangalan:',
    date: 'Petsa:',
    words: 'Basahin at isulat ang mga salita.',
    sentence: 'Basahin at isulat ang pangungusap.',
    parentNote: 'Para sa magulang o kasama sa bahay:',
  },
  landing: {
    title: 'AR.Ai: Ang Matalinong Kaakabay sa Pagbasa',
    subtitle:
      'Ang adaptive at masayang AI reading tutor para sa mga batang Pilipino. Matutong magbasa sa sariling bilis at paraan!',
    infoLabel: 'About AR.AI',
    close: 'Close',
    modalTitle: 'Mga Tampok sa AR.AI',
    badges: ['100% Offline & Private', 'Powered by Local AI (Ollama, Gemma 4)', 'Key Stage 1 (Grades 1-3) Ready'],
    features: [
      {
        title: 'Maikling Babasahin (Adaptive Stories)',
        text: 'Mga kuwentong Filipino na ginagawa mismo sa device, ayon sa hilig ng bawat bata.',
      },
      {
        title: 'Tile Board Practice (Interactive Practice)',
        text: 'Pagbuo ng salita gamit ang mga tile ng titik at pantig, ayon sa Marungko method.',
      },
      {
        title: 'Buod at Printable Worksheets (Teacher Reports)',
        text: 'Awtomatikong buod para sa tutor at worksheet na maiuuwi para sa pagsasanay sa bahay.',
      },
    ],
    cta: 'Magsimula / Pumasok bilang Tutor',
  },
  header: {
    privacy: '100% Offline | Ligtas ang Datos',
    logoAlt: 'AR.AI',
    sound: 'Tunog ng laro',
    contrast: 'Mas malinaw na kulay',
  },
  apiMode: {
    mock: 'Demo na datos (offline)',
    server: 'Gamit ang server',
    fallback: 'Hindi maabot ang server. Demo na datos muna.',
  },
  lesson: {
    // From rules.json feedback_templates SHOW_ANSWER (reviewed Filipino), not new text.
    yourTurn: 'Ngayon, ikaw naman ang bumuo.',
  },
  turnSwitch: {
    start: 'Magsimula',
    avatar: (name) => `Larawan ni ${name}`,
  },
  // For the tutor and parents. English for now: a Filipino speaker translates these (CLAUDE.md: no invented Tagalog).
  tutorNotes: {
    lesson: (style, skill, reason) =>
      `Tutor: ${reason === 'reteach' ? 're-teaching' : 'teaching'} "${skill}" (${{ visual: 'visual', steps: 'step by step', story: 'story', letters: 'letter sounds' }[style]}) before practice.`,
    placement: () => 'Tutor: diagnostic item (one try, no hints) to find where this learner starts.',
    reteach: (note) => `Tutor: re-teaching with a new approach. ${note ?? ''}`.trim(),
    easy: () => 'Tutor: an easier item after a hard or slow answer.',
  },
  signup: {
    subtitle: 'For the tutor',
    title: 'Who are the learners?',
    tutorName: 'Your name (tutor)',
    childName: (n) => `Learner ${n}: first name`,
    firstNameOnly: 'First name only',
    picture: 'Picture',
    interests: (n, max) => `What does this learner like? (${n} of ${max})`,
    diagnostic: 'Start with a short diagnostic (finds where this learner starts)',
    addChild: 'Add a learner',
    remove: (who) => `Remove ${who}`,
    needed: "Add each learner's first name and at least one interest.",
    ready: (n) => `${n} learner${n === 1 ? '' : 's'} ready.`,
    save: 'Save the group',
    cancel: 'Back',
    newGroup: 'New group',
  },
  streak: (n) => `${n} in a row`,
  // The practice dashboard (TileBoardScreen). Learner-facing Filipino from the design spec; the tutor badge is English.
  dashboard: {
    role: 'Mag-aaral',
    stars: (n) => `${n} Bituin`,
    nav: { practice: 'Pagsasanay', stories: 'Mga Kwento', progress: 'Aking Progress' },
    navLabel: 'Learner menu',
    tip: 'Tip: Pakinggan muna ang tunog bago piliin ang tamang titik!',
    mode: {
      placement: 'Tutor: Diagnostic Item',
      practice: 'Tutor: Practice',
      reteach: 'Tutor: Re-teach',
      easy: 'Tutor: Easier item',
    },
    noStory: 'No story for this learner yet.',
  },
  quizResult: {
    title: 'Quiz result',
    levelUp: (level) => `Next story: level ${level} (harder)`,
    levelSame: (level) => `Next story: level ${level} (same)`,
    levelDown: (level) => `Next story: level ${level} (easier)`,
    writing: 'A new personal story is being written for the next session.',
    nextLearner: 'Next learner',
  },
  profile: {
    open: 'Progress',
    title: (name) => `${name}'s progress`,
    forParents: 'For the tutor and parents',
    back: 'Back to summary',
    interests: 'Interests',
    level: 'Story level',
    pace: 'Pace',
    paces: { fast: 'fast', steady: 'steady', slow: 'takes time' },
    diagnostic: 'Starting point',
    diagnostics: { pending: 'diagnostic not finished', done: 'diagnostic done' },
    now: 'Working on now',
    mastered: 'Mastered',
    strengths: 'Getting stronger',
    needsWork: 'Needs more practice',
    methods: 'Teaching approaches tried',
    worked: 'worked',
    notYet: 'did not work yet',
    running: 'in progress',
    sessions: 'Sessions (right on the first try)',
    stars: (n, streak) => `${n} stars, ${streak} in a row`,
    none: 'None yet',
    chartTitle: 'Skills mastered after each session',
    chartLabel: (n, total, sessions) => `${n} of ${total} skills mastered after ${sessions} session(s)`,
    chartPoint: (date, n, total, acc) =>
      `${date}: ${n} of ${total} skills mastered${acc == null ? '' : `, ${Math.round(acc * 100)}% right on the first try`}`,
    ladder: 'Reading ladder (vowels first)',
    backToPractice: 'Back to practice',
  },
}
