// All user-facing UI text (Filipino). Feedback lines come from the API.
export const t = {
  loading: 'Sandali lang...',
  loadingSession: 'Inihahanda ang sesyon...',
  loadingStory: 'Inihahanda ang kuwento...',
  loadingSummary: 'Ginagawa ang buod...',
  loadError: 'May problema. Subukan muli.',
  retry: 'Subukan muli',
  turnLabel: (n) => `Tanong ${n}`,
  learnerTurn: (name) => `Ikaw na, ${name}!`,
  listen: 'Pakinggan',
  instructions: {
    dictation_letters: 'Pakinggan ang salita. Buuin gamit ang mga titik.',
    dictation_syllables: 'Pakinggan ang salita. Buuin gamit ang mga pantig.',
    missing_letter: 'Pakinggan ang salita. Anong titik ang kulang?',
    sentence_builder: 'Pakinggan. Ayusin ang mga salita.',
  },
  modelLabel: 'Tingnan:',
  slotsLabel: 'Mga kahon para sa sagot',
  trayLabel: 'Mga tile na pagpipilian',
  emptySlot: (n) => `Bakanteng kahon ${n}`,
  fixedTile: (text, n) => `${text}, nakalagay na sa kahon ${n}`,
  placedTile: (text, n) => `${text}, nasa kahon ${n}. Pindutin para alisin.`,
  availableTile: (text) => `${text}. Pindutin para ilagay.`,
  clear: 'Burahin',
  check: 'Suriin',
  next: 'Susunod',
  // Generic fallback from CLAUDE.md, used while the API sends no feedback for wrong attempts.
  tryAgain: (name) => `Subukan natin ulit, ${name}!`,
  overlay: {
    title: 'Malapit na!',
    hints: {
      replay_by_syllable: 'Pakinggan ulit ang bawat pantig.',
      highlight_slot: 'Tingnan ang kahong may ilaw.',
      first_tile: 'Magsimula tayo sa unang kahon.',
    },
    retry: 'Subukan ulit',
    listenAgain: 'Pakinggan ulit',
    showAnswer: 'Ipakita ang sagot',
  },
  phases: {
    readAlong: 'Sabay na pagbasa',
    tiles: 'Mga tile',
    stories: 'Mga tanong sa kuwento',
  },
  tutorBar: {
    tutor: 'Tutor',
    skip: 'Laktawan',
    timeLeft: (time) => `Natitirang oras: ${time}`,
    timeUp: 'Tapos na ang oras',
  },
  login: {
    title: 'Pasok ng Tutor',
    prompt: 'Ilagay ang iyong PIN',
    digit: (d) => `Numero ${d}`,
    filled: (n, total) => `${n} sa ${total} numero`,
    delete: 'Bura',
    deleteLabel: 'Burahin ang huling numero',
    enter: 'Pumasok',
    demoNote: 'Demo: puwede ang kahit anong PIN.',
    error: 'May problema sa PIN. Subukan muli.',
  },
  group: {
    greeting: (name) => `Magandang araw, ${name}!`,
    question: 'Sino ang narito ngayon?',
    present: 'Narito',
    absent: 'Wala',
    count: (n) => `${n} bata ang narito.`,
    needOne: 'Pumili ng kahit isang bata.',
    start: 'Simulan ang sesyon',
  },
  readAlong: {
    heading: 'Sabay tayong magbasa',
    instruction: 'Pakinggan ang kuwento.',
    echo: 'Ngayon, sabay-sabay nating basahin!',
    repeat: 'Muling Pakinggan',
    nextParagraph: 'Susunod na talata',
    done: 'Tapos na',
    paragraphOf: (i, n) => `Talata ${i} ng ${n}`,
  },
  story: {
    listen: 'Pakinggan ang tanong',
    instruction: 'Piliin ang tamang sagot.',
    choicesLabel: 'Mga pagpipilian',
  },
  summary: {
    subtitle: 'Para sa tutor',
    title: 'Buod ng sesyon',
    nextFocus: 'Susunod na pagtuunan:',
    groupNote: 'Paalala sa grupo:',
    newSession: 'Bagong sesyon',
  },
  progress: {
    stars: (n) => `${n} bituin`,
    questions: (n, total) => `${n} sa ${total} tanong`,
  },
  sheet: {
    print: 'Ilimbag ang Magsanay Sheet',
    preparing: 'Inihahanda...',
    title: 'Magsanay Tayo!',
    name: 'Pangalan:',
    date: 'Petsa:',
    words: 'Basahin at isulat ang mga salita.',
    sentence: 'Basahin at isulat ang pangungusap.',
    parentNote: 'Para sa magulang o kasama sa bahay:',
  },
  header: {
    privacy: '100% Offline | Ligtas ang Datos',
    logoAlt: 'AR.AI',
    sound: 'Tunog ng laro',
    contrast: 'Mas malinaw na kulay',
  },
  apiMode: {
    mock: 'Demo na datos (offline)',
    server: 'Gamit ang server',
    fallback: 'Hindi maabot ang server. Demo na datos muna.',
  },
  turnSwitch: {
    start: 'Magsimula',
    avatar: (name) => `Larawan ni ${name}`,
  },
}
